public class Strings{
    // concatination is possible 
    //
    public String largestOddNumber(String num){

        int n  = num
    }

    public static void main(String[] main){
        System.out.println("HI");
        String s = "coding ";
        String msg = "Hello" + s.length();
        
        System.out.println(msg);
        System.out.println(((Object)s.length()).getClass());
        // java.lang.integer is the output in this 
        // String builder are fazt and mutable 
        // StringBuilder sb - 
    }
}